build:
  tests:
    override:
      - command: './vendor/bin/phpunit --coverage-clover=coverage.clover'
        coverage:
          file: 'coverage.clover'
          format: 'clover'
checks:
  php:
    code_rating: true
    duplication: true
tools:
  external_code_coverage:
    timeout: 600
    runs: 3
